### ISSUE TITLE
[Bug]: SessionBasedFixture Setup is flaky during testing

### ISSUE THREAD

**Issue by matthew-wiemer** [relativitydev/relativity.testing.framework.api#199]
### Describe the bug

An internal server error is hit at some point during the SessionBasedFixture's setup.

Example: 

```
Error Message:
   Relativity.Testing.Framework.Api.Arrangement.TestArrangeException : Test arrange failed.
  ----> System.Net.Http.HttpRequestException : StatusCode: 500, ReasonPhrase: 'Internal Server Error', Version: 1.1, Content: System.Net.Http.StreamContent, Headers:
{
  X-Kepler-Version: 2.0
  TrackingID: 
  X-Frame-Options: SAMEORIGIN
  Referrer-Policy: no-referrer
  Content-Security-Policy: frame-ancestors 'self'
  X-Content-Type-Options: nosniff
  Strict-Transport-Security: max-age=31536000; includeSubDomains
  Cache-Control: private
  Date: Tue, 28 Sep 2021 16:25:57 GMT
  Server: Microsoft-HTTPAPI/2.0
  X-AspNet-Version: 4.0.30319
  Content-Length: 103
  Content-Type: application/json; charset=utf-8
}

Content text: {"ErrorType":"Relativity.Services.Exceptions.ServiceException","Identifier":"","Message":"Read Failed"}
  Stack Trace:
     at Relativity.Testing.Framework.Api.Arrangement.SessionBasedFixture.Arrange(Action action) in D:\a\relativity.testing.framework.api\relativity.testing.framework.api\source\Relativity.Testing.Framework.Api\Arrangement\SessionBasedFixture.cs:line 191
   at Relativity.Testing.Framework.Api.Arrangement.SessionBasedFixture.ArrangeWorkingWorkspace(Action`1 action) in D:\a\relativity.testing.framework.api\relativity.testing.framework.api\source\Relativity.Testing.Framework.Api\Arrangement\SessionBasedFixture.cs:line 214
   at Relativity.Testing.Framework.Api.FunctionalTests.Strategies.LayoutAddFieldsStrategy.AddFields_AddSingleField() in D:\a\relativity.testing.framework.api\relativity.testing.framework.api\source\Relativity.Testing.Framework.Api.FunctionalTests\Strategies\Layouts\LayoutAddFieldsStrategyFixture.cs:line 31
--HttpRequestException
   at Relativity.Testing.Framework.Api.Services.HttpService.CheckResponseStatus(HttpResponseMessage response) in D:\a\relativity.testing.framework.api\relativity.testing.framework.api\source\Relativity.Testing.Framework.Api\Services\HttpService.cs:line 159
   at Relativity.Testing.Framework.Api.Services.HttpService.HandleHttpResponseMessage[TResult](HttpResponseMessage response) in D:\a\relativity.testing.framework.api\relativity.testing.framework.api\source\Relativity.Testing.Framework.Api\Services\HttpService.cs:line 106
   at Relativity.Testing.Framework.Api.Services.HttpService.Send[TResult](HttpMethod method, String relativeUri, Object content, Double timeout, UserCredentials userCredentials) in D:\a\relativity.testing.framework.api\relativity.testing.framework.api\source\Relativity.Testing.Framework.Api\Services\HttpService.cs:line 93
   at Relativity.Testing.Framework.Api.Services.HttpService.Post[TResult](String relativeUri, Object content, Double timeout, UserCredentials userCredentials) in D:\a\relativity.testing.framework.api\relativity.testing.framework.api\source\Relativity.Testing.Framework.Api\Services\HttpService.cs:line 49
   at Castle.Proxies.Invocations.IHttpService_Post.InvokeMethodOnTarget()
   at Castle.DynamicProxy.AbstractInvocation.Proceed()
   at Relativity.Testing.Framework.Logging.LoggingInterceptor.Intercept(IInvocation invocation)
   at Castle.DynamicProxy.AbstractInvocation.Proceed()
   at Castle.Proxies.IHttpServiceProxy.Post[TResult](String relativeUri, Object content, Double timeout, UserCredentials userCredentials)
   at Relativity.Testing.Framework.Api.Strategies.LayoutCreateStrategyV1.SendRequest(Int32 workspaceId, Object dto, Layout entity) in D:\a\relativity.testing.framework.api\relativity.testing.framework.api\source\Relativity.Testing.Framework.Api\Strategies\Layouts\LayoutCreateStrategyV1.cs:line 22
   at Relativity.Testing.Framework.Api.Strategies.Layouts.LayoutCreateAbstractStrategy.DoCreate(Int32 workspaceId, Layout entity) in D:\a\relativity.testing.framework.api\relativity.testing.framework.api\source\Relativity.Testing.Framework.Api\Strategies\Layouts\LayoutCreateAbstractStrategy.cs:line 25
   at Relativity.Testing.Framework.Api.Strategies.CreateWorkspaceEntityStrategy`1.Create(Int32 workspaceId, T entity) in D:\a\relativity.testing.framework.api\relativity.testing.framework.api\source\Relativity.Testing.Framework.Api\Strategies\CreateWorkspaceEntityStrategy`1.cs:line 27
   at Castle.Proxies.Invocations.ICreateWorkspaceEntityStrategy`1_Create_1.InvokeMethodOnTarget()
   at Castle.DynamicProxy.AbstractInvocation.Proceed()
   at Relativity.Testing.Framework.Logging.LoggingInterceptor.Intercept(IInvocation invocation)
   at Castle.DynamicProxy.AbstractInvocation.Proceed()
   at Relativity.Testing.Framework.Api.Interceptors.ApplicationInsightsEventInterceptor.Intercept(IInvocation invocation) in D:\a\relativity.testing.framework.api\relativity.testing.framework.api\source\Relativity.Testing.Framework.Api\Interceptors\ApplicationInsightsEventInterceptor.cs:line 41
   at Castle.DynamicProxy.AbstractInvocation.Proceed()
   at Relativity.Testing.Framework.Api.Interceptors.RetryInterceptor.ExecuteRetry(IInvocation invocation, Int32 retryCount) in D:\a\relativity.testing.framework.api\relativity.testing.framework.api\source\Relativity.Testing.Framework.Api\Interceptors\RetryInterceptor.cs:line 45
   at Relativity.Testing.Framework.Api.Interceptors.RetryInterceptor.Intercept(IInvocation invocation) in D:\a\relativity.testing.framework.api\relativity.testing.framework.api\source\Relativity.Testing.Framework.Api\Interceptors\RetryInterceptor.cs:line 22
   at Castle.DynamicProxy.AbstractInvocation.Proceed()
   at Castle.Proxies.ICreateWorkspaceEntityStrategy`1Proxy_3.Create(Int32 workspaceId, Layout entity)
   at Relativity.Testing.Framework.Api.Arrangement.WorkspaceLevelEntityCreator.Create[TEntity](TEntity entity) in D:\a\relativity.testing.framework.api\relativity.testing.framework.api\source\Relativity.Testing.Framework.Api\Arrangement\WorkspaceLevelEntityCreator.cs:line 34
   at Relativity.Testing.Framework.Api.Arrangement.TestArrangementDomain.Create[TEntity](TEntity entity) in D:\a\relativity.testing.framework.api\relativity.testing.framework.api\source\Relativity.Testing.Framework.Api\Arrangement\TestArrangementDomain.cs:line 67
   at Relativity.Testing.Framework.Api.FunctionalTests.Strategies.LayoutAddFieldsStrategy.<>c__DisplayClass2_0.<AddFields_AddSingleField>b__0(TestArrangementDomain`1 x) in D:\a\relativity.testing.framework.api\relativity.testing.framework.api\source\Relativity.Testing.Framework.Api.FunctionalTests\Strategies\Layouts\LayoutAddFieldsStrategyFixture.cs:line 31
   at Relativity.Testing.Framework.Api.Arrangement.WorkspaceTestArrangementDomainExtensions.ArrangeWorkspace(TestArrangementDomain`1 domain, Action`1 arrangementAction) in D:\a\relativity.testing.framework.api\relativity.testing.framework.api\source\Relativity.Testing.Framework.Api\Arrangement\Extensions\WorkspaceTestArrangementDomainExtensions.cs:line 58
   at Relativity.Testing.Framework.Api.Arrangement.SessionBasedFixture.<>c__DisplayClass26_0.<ArrangeWorkingWorkspace>b__0() in D:\a\relativity.testing.framework.api\relativity.testing.framework.api\source\Relativity.Testing.Framework.Api\Arrangement\SessionBasedFixture.cs:line 214
   at Relativity.Testing.Framework.Api.Arrangement.SessionBasedFixture.Arrange(Action action) in D:\a\relativity.testing.framework.api\relativity.testing.framework.api\source\Relativity.Testing.Framework.Api\Arrangement\SessionBasedFixture.cs:line 186
```

### Steps to Reproduce

Run the feature branch Github Actions pipeline.

Expected: Success in every release.
Actual: Prairie Smoke failure with 

### Relativity.Testing.Framework Version

6.1.0

### Relativity.Testing.Framework.API Version

5.4.0

### Relativity environment installation Type

RelativityOne

### Environment version

12.2.224.7

### Test Case

https://github.com/relativitydev/relativity.testing.framework.api/blob/8ffd1845ec51a15102c609b2cd3a832ffb74cc55/source/Relativity.Testing.Framework.Api/Arrangement/SessionBasedFixture.cs

### Expected Behavior

Tests pass.

### Actual Behavior

Internal server error while arranging a workspace.

### Additional Context

See https://github.com/relativitydev/relativity.testing.framework.api/pull/181

**Comment by paulletang** [comment]
I don't think we're testing against RelativityOne in our actions, but I also don't think that's a critical piece of information in this specific bug report.

**Comment by paulletang** [comment]
Since the failing strategy here is also `LayoutCreateStrategyV1`, I suspect that this is related to the bug that Sai reported.
https://github.com/relativitydev/relativity.testing.framework.api/issues/194
